version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: back-end-helqui
    restart: unless-stopped
    environment:
      - KNEX_HOST
      - KNEX_CLIENT
      - KNEX_USER
      - KNEX_PASSWORD
      - KNEX_PORT
      - KNEX_DATABASE
      - MYSQL_DOCKER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - helqui_network

networks:
  helqui_network:
    external: true