name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      # 1. Fazer checkout do código
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Configurar o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # 3. Instalar dependências e compilar
      - name: Install and Build
        run: |
          npm install
          npm run build
