name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Get version the package.json
        id: package_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build Docker Image
        run: |
          docker build -t davjose/back-end-precification:${{ env.VERSION }} \
                       -t davjose/back-end-precification:${{ github.sha }} \
                       -t davjose/back-end-precification:latest .

      - name: Push Docker Images
        run: |
          docker push davjose/back-end-precification --all-tags

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{vars.REMOTE_HOST}}
          REMOTE_USER: ${{vars.REMOTE_USER}}
          REMOTE_PORT: ${{vars.REMOTE_PORT}}
          SCRIPT_BEFORE: |
            ls
          SCRIPT_AFTER: |
            echo "Starting deploy..."
            docker pull davjose/back-end-precification:${{ env.VERSION }}
            docker pull davjose/back-end-precification:latest
            docker stop backendprecification || true
            docker rm backendprecification || true
            cd ./helqui
            docker run -d \
              --name backendprecification \
              --env-file .env \
              --network precification_network \
              -p 3000:3000 davjose/back-end-precification:latest

            echo "Deploy completed."