name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        
      - name: Build Docker Image
        run: |
          docker build -t davjose/back-end-precification:v1.20 .
          docker build -t davjose/back-end-precification:latest .
          
      - name: Push Docker Images
        run: |
          docker push davjose/back-end-precification:v1.20
          docker push davjose/back-end-precification:latest